/* eslint-disable @typescript-eslint/no-explicit-any */
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import * as s from "@/lib/db/schema";
import { isAdmin } from "@/lib/admin-auth";
import { logout, saveRecord, deleteRecord } from "./actions";

const configs = [
  ["personal_info", "Personal information", s.personalInfo], ["summary", "Per-locale summaries", s.summaries], ["skills", "Skills by category", s.skills], ["experience", "Experience", s.experiences], ["experience_bullets", "Experience bullets", s.experienceBullets], ["projects", "Projects", s.projects], ["project_bullets", "Project bullets", s.projectBullets], ["education", "Education", s.education], ["locale_visibility_config", "Locale visibility (fa/en)", s.localeVisibilityConfig],
] as const;
async function rows(table: any) { return db.select().from(table); }
function Editor({ table, label, row }: { table: string; label: string; row?: any }) { const data = row ? Object.fromEntries(Object.entries(row).filter(([k]) => !["id","updatedAt"].includes(k))) : {}; return <form action={saveRecord} className="rounded-lg border bg-card p-4"><input type="hidden" name="table" value={table}/>{row?.id && <input type="hidden" name="id" value={row.id}/>}<div className="flex items-center justify-between gap-3"><h3 className="font-medium">{label}{row?.id ? ` #${row.id}` : ""}</h3>{row?.id && <button formAction={deleteRecord} name="table" value={table} className="text-sm text-destructive">Delete</button>}</div><textarea name="data" defaultValue={JSON.stringify(data, null, 2)} className="mt-3 min-h-28 w-full rounded-md border bg-background p-3 font-mono text-xs" aria-label={`${label} JSON`} required/><button className="mt-3 rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground">Save</button></form> }
export default async function AdminPage() { if (!(await isAdmin())) redirect("/admin/login"); const sections = await Promise.all(configs.map(async ([table,label,definition]) => [table,label,await rows(definition)] as const)); return <main className="min-h-screen bg-muted/30"><header className="sticky top-0 z-10 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><div><p className="text-xs font-medium uppercase tracking-[0.2em] text-muted-foreground">CV Studio</p><h1 className="text-xl font-semibold">Admin editor</h1></div><form action={logout}><button className="rounded-md border px-3 py-2 text-sm">Sign out</button></form></div></header><div className="mx-auto max-w-6xl space-y-8 px-6 py-8"><p className="max-w-2xl text-sm text-muted-foreground">Manage every record directly. Values are validated as JSON against the database schema before writing.</p>{sections.map(([table,label,data]) => <section key={table} className="space-y-3"><div><h2 className="text-lg font-semibold">{label}</h2><p className="text-xs text-muted-foreground">{data.length} record{data.length === 1 ? "" : "s"}</p></div><div className="grid gap-3 md:grid-cols-2">{data.map((row: any) => <Editor key={row.id} table={table} label={label} row={row}/>)}<Editor table={table} label={`New ${label.slice(0,-1)}`} /></div></section>)}</div></main> }
